packages:
  - packages/*
  - apps/*
catalog:
  '@ianvs/prettier-plugin-sort-imports': ^4.4.1
  '@tailwindcss/vite': ^4.1.3
  '@types/node': ^20.19.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@vitejs/plugin-react-swc': ^4.0.0
  ai: 5.0.48
  '@ai-sdk/gateway': 1.0.26
  '@ai-sdk/google': 2.0.15
  '@ai-sdk/openai': 2.0.32
  '@ai-sdk/provider': 2.0.0
  dotenv-cli: ^7.4.2
  prettier: ^3.5.3
  zod: 4.1.11
  react-dom: ^19.0.0
  react: ^19.0.0
  tailwindcss: ^4.1.3
  typescript: ^5.8.2
  vite-tsconfig-paths: ^5.1.4
  vite: ^6.3.5
